version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

homebrew_casks:
  - name: omcp
    repository:
      owner: jruttan1
      name: homebrew-omcp
    homepage: https://github.com/jruttan1/omcp
    description: API spec to MCP server in 1 command
    install: |
      bin.install "omcp"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
